### ISSUE TITLE
Customize VM name

### ISSUE THREAD

**Issue by eglute** [Commvault/VMC-AWS-Automation#1]
Currently we cannot customize VM name that gets deployed during SDDC onboarding workflow. The default naming scheme is "Node_1_vcenter.sddc-<ip>.vmwarevmc.com". We would like to customize the name of the VM that gets created during SDDC onboard process. 
Since we need only one node per SDDC, we do not need to have "Node_1" as part of the name either.

**Comment by cvltyeshwanthr** [comment]
I have updated workflows and postman collection to take an input name as "vmName", so now the vm name would be  "vmName_vcenter.sddc-.vmwarevmc.com".


If more than one nodes are required the workflow would automatically name them as "vmName_1_vcenter.sddc-.vmwarevmc.com", "vmName_2_vcenter.sddc-.vmwarevmc.com" etc.
